# NixOS configuration for the 2015 MacBook Pro (mbp2015-linux).
# Modeled on hosts/desktop/configuration.nix — see agents.md before editing.

{ config, lib, pkgs, ... }:

{
  # hardware-configuration.nix is generated by nixos-generate-config at
  # install time on the machine itself — not committed to the repo yet.
  imports = [
    ./hardware-configuration.nix
    ../../modules/system/shell.nix
    ../../modules/system/docker.nix
    ../../modules/system/virt-manager.nix
    ../../modules/system/housekeeping.nix
    ../../modules/system/audio.nix
  ];

  # UEFI boot: the Mac's EFI firmware works with systemd-boot.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Latest kernel like the desktop; drop back to the default (stable)
  # kernel if the newest is unstable on this hardware.
  boot.kernelPackages = pkgs.linuxPackages_latest;

  networking.hostName = "mbp2015-linux"; # Define your hostname.
  networking.networkmanager.enable = true;

  # Set your time zone.
  time.timeZone = "America/Toronto";

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.nixos_user = {
    isNormalUser = true;
    extraGroups = [ "wheel" ]; # Enable ‘sudo’ for the user.
    initialPassword = "Passw0rd!";
    packages = with pkgs; [
      tree
    ];
  };

  # List packages installed in system profile.
  # You can use https://search.nixos.org/ to find more packages (and options).
  environment.systemPackages = with pkgs; [
    vim # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
    wget
    git
  #  file   # identifies file type
    curl   # transfer data to or from using URLs
  #  gnupg  # Encrypt and signs data using openpgp
  ];

  #enable COSMIC Desktop DE
  services.displayManager.cosmic-greeter.enable = true;
  services.desktopManager.cosmic.enable = true;
  services.system76-scheduler.enable = true;

  # fonts
  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono
  ];

#  #Temp see if this fixes audio
#  security.rtkit.enable = true;
#  services.pipewire = {
#    enable = true;
#    alsa.enable = true;
#    alsa.support32Bit = true;
#    pulse.enable = true;
#    jack.enable = true; 
#  };
  # Ensure old pulse is disabled
#  services.pulseaudio.enable = false;

  # enable experimental features
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Allow unfree packages (same blanket policy as the desktop).
  nixpkgs.config.allowUnfree = true;

  # Broadcom BCM4360 wifi needs redistributable firmware — the classic
  # 2015-MacBook-Pro gotcha (see agents.md). If wifi still doesn't come up,
  # the Apple-specific brcmfmac firmware blob may be required.
  hardware.enableRedistributableFirmware = true;

  # Graphics: driven by the Intel iGPU (i915) out of the box.
  # No amdgpu config (unlike the desktop) — the discrete AMD chip stays
  # dormant on Linux, and COSMIC is intentionally not enabled here.

  system.stateVersion = "26.05";
}
